#pragma once
#include <dx12lib/Buffer/IndexBuffer.h>
#include <dx12lib/Buffer/VertexBuffer.h>
#include <dx12lib/Buffer/ConstantBuffer.h>
#include <dx12lib/Buffer/SRStructuredBuffer.h>
#include <dx12lib/Buffer/ReadbackBuffer.h>
#include <dx12lib/Buffer/FRConstantBuffer.hpp>
#include <dx12lib/Buffer/FRSRStructuredBuffer.hpp>
#include <dx12lib/Buffer/ConsumeStructuredBuffer.h>
#include <dx12lib/Buffer/AppendStructuredBuffer.h>
#include <dx12lib/Buffer/UAStructuredBuffer.h>